### ISSUE TITLE
User FAQ collections for NewSwap 1.0

### ISSUE THREAD

**Issue by evanliuchina** [newswap/newswap-web#22]
This thread is created for continuously collecting newswap 1.0 questions from the community and formulating answers for the questions. First language is in Chinese if the question is in Chinese.

Some good questions and answers can be merged into [the FAQ page of the official site](https://newswap.org/faq/) periodically.

**Comment by evanliuchina** [comment]
Q: 如何查看提供流动性获得的手续费收益？
A: 打开 https://info.newswap.org/accounts 页面，输入自己的NEW地址即可查看。在「流动资金份额」部分的「手续费总收入」列。手机屏幕宽度不够可能显示不出，建议使用大屏幕设备比如电脑查看。

示例：
![image](https://user-images.githubusercontent.com/63840843/95600056-7cc24780-0a84-11eb-8572-ffff63b0e911.png)

**Comment by arisac** [comment]
~~Selected FAQs will be moved to~~

~~https://github.com/newswap/newswap-web/wiki/FAQ-中文 & https://github.com/newswap/newswap-web/wiki/FAQ-English~~

~~website is using markdown to generate html format~~

**Comment by arisac** [comment]
@evanliuchina @micleestar

After bf2d527e694b0e60709fd641cc37ef2a5700fce5 , FAQ docs are moved to `/faq/faq.en.md` and `/faq/faq.zh.md` and start accepting PR.

Images needed in FAQ docs can be placed under the `/faq/faq-assets/` directory and add links in md files as a relative link to the file.

Updates to TestNet and Production website is current manually by creating a PR to testnet/production branch and must only to be merged by the website admin. See https://github.com/newswap/newswap-web/pulls?q=is%3Apr+is%3Aclosed as examples.

I'm currently removing checks in FAQ docs since the feature is incomplete. Please check the contents carefully by yourself.

This is a quick solution to be used temporarily. NewSwap website will be rewritten completely. But no plan for now.

This issue will be closed after new FAQ contents are deployed to production.

**Comment by arisac** [comment]
> Q: 如何查看提供流动性获得的手续费收益？
> A: 打开 https://info.newswap.org/accounts 页面，输入自己的NEW地址即可查看。在「流动资金份额」部分的「手续费总收入」列。手机屏幕宽度不够可能显示不出，建议使用大屏幕设备比如电脑查看。
> 
> 示例：
> ![image](https://user-images.githubusercontent.com/63840843/95600056-7cc24780-0a84-11eb-8572-ffff63b0e911.png)

This one has been added to FAQ with 93e5e80c083cfac6f105067728454323ac380436

**Comment by arisac** [comment]
Deployed with #40
